#ifndef APPLICATION_CONSTANTS_H
    #define APPLICATION_CONSTANTS_H

    #define MY_SDL_INIT_FLAGS (SDL_INIT_TIMER | SDL_INIT_AUDIO | SDL_INIT_VIDEO)

    #define APPLICATION_MODE_INGAME      0
    #define APPLICATION_MODE_MAINMENU    1
    #define APPLICATION_MODE_KEYBINDINGS 2
    #define APPLICATION_MODE_OPTIONS     3
    #define APPLICATION_MODE_SELECTHOLD  4
    #define APPLICATION_MODE_SAVEORLOAD  5

    #define MAXIMUM_LEVELS_IN_HOLD 250
    #define MAXIMUM_ROOMS_IN_LEVEL 250
    #define MAXIMUM_DEMO_LENGTH 32000

    #define MAXIMUM_SYSTEM_NAME_LENGTH 16
    #define MINIMUM_PLAYER_NAME_LENGTH  1
    #define MAXIMUM_PLAYER_NAME_LENGTH 30
    #define MINIMUM_HOLD_NAME_LENGTH    3
    #define MAXIMUM_HOLD_NAME_LENGTH   50
    #define MINIMUM_LEVEL_NAME_LENGTH   3
    #define MAXIMUM_LEVEL_NAME_LENGTH  50
    #define MINIMUM_ROOM_NAME_LENGTH    3
    #define MAXIMUM_ROOM_NAME_LENGTH   50
    #define MINIMUM_DEMO_NAME_LENGTH    3
    #define MAXIMUM_DEMO_NAME_LENGTH   50
#endif
