#ifndef APPLICATION_CONSTANTS_H
    #define APPLICATION_CONSTANTS_H

    #define MY_SDL_INIT_FLAGS (SDL_INIT_TIMER | SDL_INIT_AUDIO | SDL_INIT_VIDEO)

    #define APPLICATION_MODE_INGAME      0
    #define APPLICATION_MODE_MAINMENU    1
    #define APPLICATION_MODE_KEYBINDINGS 2
    #define APPLICATION_MODE_OPTIONS     3
    #define APPLICATION_MODE_SELECTHOLD  4
    #define APPLICATION_MODE_SAVEORLOAD  5
#endif
