#ifndef ENTITY_TYPES_H
    #define ENTITY_TYPES_H

    #define ENTITY_NOTHING               0
    #define ENTITY_PLAYER                1
    #define ENTITY_CLONE                 2
    #define ENTITY_COCKROACH             3
    #define ENTITY_EGG_LAYING_COCKROACH  4
    #define ENTITY_SPIDER                5
    #define ENTITY_EYEBALL               6
    #define ENTITY_MUD_DROPLET           7
    #define ENTITY_TAR_DROPLET           8
    #define ENTITY_GEL_DROPLET           9
    #define ENTITY_GOBLIN               10
    #define ENTITY_GOLEM                11
    #define ENTITY_GIANT_GOLEM          12
    #define ENTITY_BAT                  13
    #define ENTITY_WATERSKIPPER         14
    #define ENTITY_WATERSKIPPER_NEST    15
    #define ENTITY_SEEP                 16
    #define ENTITY_AUMTLICH             17
    #define ENTITY_GUARD                18
    #define ENTITY_SLAYER               19
    #define ENTITY_RATTLESNAKE          20
    #define ENTITY_ADDER                21
    #define ENTITY_WATER_SNAKE          22
    #define ENTITY_COBRA                23
    #define ENTITY_MUD_SPIRIT           24
    #define ENTITY_TAR_SPIRIT           25
    #define ENTITY_GEL_SPIRIT           26
    #define ENTITY_BRAIN                27
    #define ENTITY_FEGUNDO              28
    #define ENTITY_ASHES                29
    #define ENTITY_STALWART             30
    #define ENTITY_WUBBA                31
    #define ENTITY_CITIZEN              32
    #define ENTITY_DECOY                33
    #define ENTITY_MIMIC                34
    #define ENTITY_AUTOMATON            35
    #define ENTITY_CHARACTER            36
    #define ENTITY_MUD                  37
    #define ENTITY_TAR                  38
    #define ENTITY_GEL                  39
    #define ENTITY_BRIAR                40
    #define ENTITY_IMMATURE_BRIAR       41
    #define ENTITY_BRIAR_ROOT           42
    #define ENTITY_ORB                  43
    #define ENTITY_DAMAGED_ORB          44
    #define ENTITY_BADLY_DAMAGED_ORB    45
    #define ENTITY_GIANT_ORB            46
    #define ENTITY_BOMB                 47
    #define ENTITY_MIRROR               48
    #define ENTITY_INVISIBILITY_POTION  49
    #define ENTITY_SPEED_POTION         50
    #define ENTITY_MIMIC_POTION         51
    #define ENTITY_DECOY_POTION         52
#endif
