#ifndef GAMEPLAY_CONSTANTS_H
    #define GAMEPLAY_CONSTANTS_H

    #define MAXIMUM_MACRO_LENGTH 10

    #define DIRECTION_NORTH     0
    #define DIRECTION_NORTHEAST 1
    #define DIRECTION_SOUTHEAST 2
    #define DIRECTION_SOUTH     3
    #define DIRECTION_SOUTHWEST 4
    #define DIRECTION_NORTHWEST 5
    #define FORCE_ARROW_NONE    6

    #define STEP_BLOCKER_NONE          0
    #define STEP_BLOCKER_POSITIVE_AXIS 1
    #define STEP_BLOCKER_NEGATIVE_AXIS 2
    #define STEP_BLOCKER_ALL           3

    #define BOMB_BLAST_RADIUS 4
#endif
