#ifndef GAMEPLAY_CONSTANTS_H
    #define GAMEPLAY_CONSTANTS_H

    #define MAXIMUM_MACRO_LENGTH 10

    #define DIRECTION_NORTH     0
    #define DIRECTION_NORTHEAST 1
    #define DIRECTION_SOUTHEAST 2
    #define DIRECTION_SOUTH     3
    #define DIRECTION_SOUTHWEST 4
    #define DIRECTION_NORTHWEST 5

    #define BOMB_BLAST_RADIUS 4
#endif
