#ifndef GRAPHICS_CONSTANTS_H
    #define GRAPHICS_CONSTANTS_H

    #define DEFAULT_DISPLAY_WIDTH 1016
    #define DEFAULT_DISPLAY_HEIGHT 720
    #define DEFAULT_SDL_DISPLAY_MODE_FLAGS (SDL_HWSURFACE | SDL_DOUBLEBUF)

    #define HEX_IMAGE_WIDTH 26
    #define HEX_IMAGE_HEIGHT 23
    #define HEX_SEPARATION_X 19
    #define HEX_SEPARATION_Y 22
#endif
